- name: Add VM instance to known hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get host key
      command: "ssh-keyscan {{ hostvars['vm_instance']['ansible_host'] }}"
      register: host_key
    - name: Add host key to known_hosts file
      known_hosts:
        name: "{{ hostvars['vm_instance']['ansible_host'] }}"
        key: "{{ host_key.stdout }}"
        state: present

- name: Install security agent on virtual machine instance
  hosts: vm_instance
  become: true
  vars:
    src_path: "{{ src_path }}"
    token: "{{ token }}"
  tasks:
    - name: Create the /opt/csg_security_agent directory
      file:
        path: /opt/csg_security_agent
        state: directory
    
    - name: Copy security agent installer to virtual machine
      copy:
        src: "{{ src_path }}/security_agent_installer_linux_amd64_v1.0.0.sh"
        dest: /opt/csg_security_agent/security_agent_installer.sh
        mode: '0755'

    - name: Copy security agent configuration to virtual machine
      copy:
        src: "{{ src_path }}/security_agent_config.conf"
        dest: /opt/csg_security_agent/security_agent_config.conf

    - name: Update the token in config file
      replace:
        path: /opt/csg_security_agent/security_agent_config.conf
        regexp: "__SECURITY_AGENT_TOKEN__"
        replace: "{{ token }}"

    - name: Install security agent
      shell: /opt/csg_security_agent/security_agent_installer.sh --config /opt/csg_security_agent/security_agent_config.conf --token "{{ token }}"
      register: install_output

    - name: Print command output
      debug:
        var: install_output.stdout_lines